[package]
name = "flyconomy"
version = "0.1.0"
edition = "2021"
description = "A simple economic simulation game about managing an airline with real-world data."
authors = ["Christian <chriamue@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/chriamue/flyconomy"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.docs.rs]
features = ["ai"]

[features]
default = ["ai"]
ai = ["rurel"]

[dependencies]
bevy = { version = "0.10.1", default-features = false, features = [
    "bevy_asset",
    "jpeg",
    "png",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_pbr",
    "bevy_text",
    "bevy_winit",
    "x11",
] }
bevy_common_assets = { version = "0.6.0", features = ["yaml", "json"] }
bevy_egui = { version = "0.20.2" }
bevy_mod_paramap = { git = "https://github.com/nicopap/bevy_mod_paramap" }
bevy_mod_picking = { version = "0.13.0", default-features = false, features = ["selection", "backend_raycast", "backend_egui"] }
bevy_obj = { version = "0.10.1" }
bevy_panorbit_camera = { version = "0.5.2", features = ["bevy_egui"] }
bevy_polyline = { version = "0.6.0" }
csv = "1.2.2"
geo = "0.25.0"
rurel = { version = "0.4.0", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
structopt = "0.3.26"
thiserror = "1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
web-sys = { version = "0.3", features = ['Blob', 'Url', 'Window', 'HtmlAnchorElement'] }
js-sys = "0.3"
